Worked on run.bat, created Windows bash script.
It is difficult or impossible to do everything I want to do with the
Windows shell alone, so I'll just ship a copy of bash.exe and write the
rest of the script in bash.

diff --git a/linux/run b/linux/run
--- a/linux/run
+++ b/linux/run
@@ -3,28 +3,28 @@
 
 # Make sure we're root.
 [[ $UID == 0 || $EUID == 0 ]] || (
-        echo "Must be root!"
-        exit 1
-        ) || exit 1
+  echo "Must be root!"
+  exit 1
+  ) || exit 1
 
 # Where should we store the data?
 savedir=$1
 [[ -n $savedir ]] || (
-    echo -n "Directory to store data: "
-    read savedir
-    [[ -d $savedir ]] || mkdir -p "$savedir" || (
-        echo "Not a valid directory."
-        exit 1
-        ) || exit 1
+  echo -n "Directory to store data: "
+  read savedir
+  [[ -d $savedir ]] || mkdir -p "$savedir" || (
+    echo "Not a valid directory."
+    exit 1
     ) || exit 1
+  ) || exit 1
 
 # Where are our binaries?
 bin="$(pwd)/tools/$(uname -m)/bin"
 [[ -d $bin ]] || ( 
-    echo "Linux IR binaries cannot be found."
-    echo "This script must be run inside its own directory."
-    exit 1
-    ) || exit 1
+  echo "Linux IR binaries cannot be found."
+  echo "This script must be run inside its own directory."
+  exit 1
+  ) || exit 1
 
 # Create directory structure.
 saveto="$savedir/$(hostname)-$(date +%Y.%m.%d-%H.%M.%S)"
